/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mes.event.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProfileDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 50211056044930151L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProfileDTO\",\"namespace\":\"com.mes.event.dto\",\"fields\":[{\"name\":\"merchantName\",\"type\":\"string\",\"default\":\"null\"},{\"name\":\"status\",\"type\":\"boolean\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProfileDTO> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProfileDTO> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProfileDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProfileDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProfileDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProfileDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProfileDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProfileDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProfileDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence merchantName;
  private boolean status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProfileDTO() {}

  /**
   * All-args constructor.
   * @param merchantName The new value for merchantName
   * @param status The new value for status
   */
  public ProfileDTO(java.lang.CharSequence merchantName, java.lang.Boolean status) {
    this.merchantName = merchantName;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return merchantName;
    case 1: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: merchantName = (java.lang.CharSequence)value$; break;
    case 1: status = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'merchantName' field.
   * @return The value of the 'merchantName' field.
   */
  public java.lang.CharSequence getMerchantName() {
    return merchantName;
  }


  /**
   * Sets the value of the 'merchantName' field.
   * @param value the value to set.
   */
  public void setMerchantName(java.lang.CharSequence value) {
    this.merchantName = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public boolean getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(boolean value) {
    this.status = value;
  }

  /**
   * Creates a new ProfileDTO RecordBuilder.
   * @return A new ProfileDTO RecordBuilder
   */
  public static com.mes.event.dto.ProfileDTO.Builder newBuilder() {
    return new com.mes.event.dto.ProfileDTO.Builder();
  }

  /**
   * Creates a new ProfileDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProfileDTO RecordBuilder
   */
  public static com.mes.event.dto.ProfileDTO.Builder newBuilder(com.mes.event.dto.ProfileDTO.Builder other) {
    if (other == null) {
      return new com.mes.event.dto.ProfileDTO.Builder();
    } else {
      return new com.mes.event.dto.ProfileDTO.Builder(other);
    }
  }

  /**
   * Creates a new ProfileDTO RecordBuilder by copying an existing ProfileDTO instance.
   * @param other The existing instance to copy.
   * @return A new ProfileDTO RecordBuilder
   */
  public static com.mes.event.dto.ProfileDTO.Builder newBuilder(com.mes.event.dto.ProfileDTO other) {
    if (other == null) {
      return new com.mes.event.dto.ProfileDTO.Builder();
    } else {
      return new com.mes.event.dto.ProfileDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProfileDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProfileDTO>
    implements org.apache.avro.data.RecordBuilder<ProfileDTO> {

    private java.lang.CharSequence merchantName;
    private boolean status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mes.event.dto.ProfileDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.merchantName)) {
        this.merchantName = data().deepCopy(fields()[0].schema(), other.merchantName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ProfileDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mes.event.dto.ProfileDTO other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.merchantName)) {
        this.merchantName = data().deepCopy(fields()[0].schema(), other.merchantName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'merchantName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMerchantName() {
      return merchantName;
    }


    /**
      * Sets the value of the 'merchantName' field.
      * @param value The value of 'merchantName'.
      * @return This builder.
      */
    public com.mes.event.dto.ProfileDTO.Builder setMerchantName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.merchantName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantName' field has been set.
      * @return True if the 'merchantName' field has been set, false otherwise.
      */
    public boolean hasMerchantName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'merchantName' field.
      * @return This builder.
      */
    public com.mes.event.dto.ProfileDTO.Builder clearMerchantName() {
      merchantName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public boolean getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.mes.event.dto.ProfileDTO.Builder setStatus(boolean value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.mes.event.dto.ProfileDTO.Builder clearStatus() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProfileDTO build() {
      try {
        ProfileDTO record = new ProfileDTO();
        record.merchantName = fieldSetFlags()[0] ? this.merchantName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.Boolean) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProfileDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProfileDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProfileDTO>
    READER$ = (org.apache.avro.io.DatumReader<ProfileDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.merchantName);

    out.writeBoolean(this.status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.merchantName = in.readString(this.merchantName instanceof Utf8 ? (Utf8)this.merchantName : null);

      this.status = in.readBoolean();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.merchantName = in.readString(this.merchantName instanceof Utf8 ? (Utf8)this.merchantName : null);
          break;

        case 1:
          this.status = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










