{{- if not .Values.deployment.type -}}
apiVersion: v1
kind: Secret
metadata:
  name: consul-info
type: Opaque
stringData:
  APPLICATION_NAME: "consumer"
  CONSUL_KV_PREFIX: "consul_kv_prefix"
  SPRING_CONSUL_HTTP_ADDR: "consul.com"
  SPRING_CONSUL_HTTP_PORT: "443"
  SPRING_CONSUL_HTTP_SCHEME: "https"
  SPRING_PROFILES_ACTIVE: "development"
data:
  CONSUL_HTTP_TOKEN: {{ .Values.consulInfo.token | b64enc }}
{{- end}}