apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
{{- if not .Values.deployment.type }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports: {{ toYaml .Values.service.ports | nindent 4 }}
        