{{- if not .Values.deployment.type -}}
apiVersion: v1
kind: Secret
metadata:
  name: vault-info
type: Opaque
stringData:
  VAULT_KV_CONTEXT: "vault_kv_context"
  VAULT_KV_BACKEND: "kv"
  VAULT_ADDR: "https://vault.com/"
data:
  VAULT_TOKEN: {{ .Values.vaultInfo.token | b64enc }}
{{- end}}